#!/usr/bin/env bash

set -e

install() {
    sudo apt-get install --yes $@
}

backup_conf() {
	# Do not backup if it's a symbolic link (installed by this script)
	[ ! -L $1 ] && mv $1 $1.backup
}

## BEGIN Realpath
install realpath
## END Realpath


## BEGIN  Vim 
# Installation
install vim python-flake8

# Configuration
[ -f $HOME/.vimrc ] && backup_conf $HOME/.vimrc
ln -s `realpath my_confs/vimrc` $HOME/.vimrc

[ -d $HOME/.vim/bundle ] || git clone https://github.com/VundleVim/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
vim +PluginInstall +qall
## END Vim


## Chromium
install chromium-browser


## Terminator
install terminator
mkdir -p $HOME/.config/terminator/
[ -f $HOME/.config/terminator/config ] && backup_conf $HOME/.config/terminator/config
ln -s `realpath my_confs/terminator_config` $HOME/.config/terminator/config

## Oh my zsh
install zsh
[ -f $HOME/.zshrc ] && backup_conf $HOME/.zshrc
ln -s `realpath my_confs/zshrc` $HOME/.zshrc
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
