#!/usr/bin/env bash

set -e

install() {
    sudo apt-get install --yes $@
}

backup_conf() {
	# Do not backup if it's a symbolic link (installed by this script)
	if [ ! -L $1 ]; then mv $1 $1.backup; fi
}

link() {
	ln -f -s $@
}

## BEGIN Realpath
install realpath
## END Realpath

## BEGIN  Vim 
install vim python-flake8

if [ -f $HOME/.vimrc ]; then backup_conf $HOME/.vimrc; fi
link `realpath my_confs/vimrc` $HOME/.vimrc

if [ ! -d $HOME/.vim/bundle ]
then
	git clone https://github.com/VundleVim/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
fi
vim +PluginInstall +qall
## END Vim

## BEGIN Terminator
install terminator
mkdir -p $HOME/.config/terminator/
if [ -f $HOME/.config/terminator/config ]; then backup_conf $HOME/.config/terminator/config; fi
link `realpath my_confs/terminator_config` $HOME/.config/terminator/config
## END Termintor

## BEGIN Oh my zsh
install zsh curl xclip
if [ -f $HOME/.zshrc ]; then backup_conf $HOME/.zshrc; fi
# Do not call env zsh
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | fgrep -v 'env zsh')"
link `realpath my_confs/zshrc` $HOME/.zshrc
## END Oh my zsh

## BEGIN git
git config --global core.excludesfile `realpath my_confs/gitignore`
## END git
