" Vundle setup {{{
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'tmhedberg/SimpylFold'
Plugin 'scrooloose/syntastic'
Plugin 'nvie/vim-flake8'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'jiangmiao/auto-pairs'
Plugin 'vim-scripts/taglist.vim'
Plugin 'Lokaltog/powerline', {'rtp': 'powerline/bindings/vim/'}
Plugin 'jlanzarotta/bufexplorer'

call vundle#end()
filetype plugin indent on " }}}

" Folding config {{{
" Enable folding
set foldmethod=indent
set foldlevel=99
" Enable folding with the spacebar
nnoremap <space> za
" }}}

au BufNewFile,BufRead *.py
			\set tabstop=4
			\set softtabstop=4
			\set shiftwidth=4
			\set textwidth=79
			\set expandtab
			\set autoindent
			\set fileformat=unix

au BufNewFile,BufRead *.yaml,*yml set
			\ tabstop=2
			\ softtabstop=2
			\ shiftwidth=2
			\ expandtab

au BufNewFile,BufRead *.js,*.html,*.css,*.twig,*.php set expandtab

" utf8 support
set encoding=utf8

" Enable wildmenu (instead of using nerdtree)
set wildmenu

" General vim config
let python_highlight_all=1
syntax on
set ignorecase
set nu
set hlsearch
set incsearch
" Remove hilight on C-l
nnoremap <silent> <C-l> :nohl<CR><C-l>

" Buffer explorer
map <C-b> :BufExplorer<CR>

" Run Flake8 on writting a Python FIle
au BufWritePost *.py call Flake8()

" Tab characteres 4-spaces-wide
set tabstop=4
set shiftwidth=4

" Boilerplate code
augroup boilerplate
au BufNewFile *.py 0put =\"#!/usr/bin/env python\<nl># -*- coding: utf-8 -*-\<nl>\<nl>\"|$
au BufNewFile *.sh 0put =\"#!/usr/bin/env bash\<nl>\<nl>\"|$
augroup END

" TagList config {{{
let Tlist_GainFocus_On_ToggleOpen = 1
let Tlist_Close_On_Select = 1
let Tlist_Use_Right_Window = 1
let Tlist_File_Fold_Auto_Close = 1
map <C-t> :TlistToggle<CR>
" }}}

" Highlight and match extra whites space {{{
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
" }}}

" Syntastic: disable on python file: let vim-flake8 do the job {{{
" let g:syntastic_disabled_filetypes=['py']
let g:syntastic_mode_map = {
    \ "mode": "active",
    \ "passive_filetypes": ["py", "python"] }
" }}}
